from pathlib import Path
from .db import connect
def _document_vocabulary_lines(db, document_id):
 rows=db.execute("SELECT v.word,v.pinyin FROM document_vocabulary_links l JOIN vocabularies v ON v.id=l.vocabulary_id WHERE l.document_id=? ORDER BY v.word",(document_id,)).fetchall()
 return "\n".join(f"- [[{word}]] — {pinyin or '-'}" for word,pinyin in rows) or "- None"

def safe(s): return ''.join(c if c.isalnum() or c in ' -_' else '_' for c in s).strip()[:120] or 'untitled'
def yaml_scalar(value):
 value=str(value).replace('\\','\\\\').replace('"','\\\"').replace('\n',' ')
 return '"'+value+'"'
def write_atomic(path,text):
 path=Path(path); tmp=path.with_suffix(path.suffix+'.tmp'); tmp.write_text(text,encoding='utf-8'); tmp.replace(path)
def write_markdown(result,root):
 p=Path(root)/'documents'; p.mkdir(parents=True,exist_ok=True); out=p/(safe(result.document.id)+'.md')
 tags=', '.join(yaml_scalar(x) for x in result.tags)
 ents='\n'.join('- [['+e.name+']] ('+e.entity_type+')' for e in result.entities) or '- None'
 rels='\n'.join('- [['+x.source+']] - '+x.relation+' -> [['+x.target+']]' for x in result.relations) or '- None'
 text=('---\n'+'id: '+yaml_scalar(result.document.id)+'\n'+'title: '+yaml_scalar(result.document.title)+'\n'+'source: '+yaml_scalar(result.document.source)+'\n'+'importance: '+str(result.importance)+'\n'+'document_type: '+yaml_scalar(result.document_type)+'\n'+'tags: ['+tags+']\n---\n\n# '+result.document.title+'\n\n## Summary\n'+result.summary+'\n\n## Korean\n'+result.translation_ko+'\n\n## Entities\n'+ents+'\n\n## Relations\n'+rels+'\n\n## Vocabulary\n'+_document_vocabulary_lines(connect(), result.document.id)+'\n')
 write_atomic(out,text)
def write_entities(entities,root):
 root=Path(root)/'entities'
 for e in entities:
  p=root/safe(e.entity_type); p.mkdir(parents=True,exist_ok=True); out=p/(safe(e.name)+'.md')
  aliases=', '.join(yaml_scalar(x) for x in e.aliases)
  write_atomic(out,
   '---\nname: '+yaml_scalar(e.name)+'\ntype: '+yaml_scalar(e.entity_type)+'\naliases: ['+aliases+']\nconfidence: '+str(e.confidence)+'\n---\n\n# '+e.name+'\n\n## Aliases\n'+('\n'.join('- '+x for x in e.aliases) or '- None')+'\n\n## Mentioned in\n- See document backlinks generated by the knowledge pipeline.\n')


def _table_exists(db, name):
    row = db.execute("SELECT 1 FROM sqlite_master WHERE type='table' AND name=?", (name,)).fetchone()
    return row is not None

def write_entities_from_db(db, root):
    root = Path(root) / "entities"
    root.mkdir(parents=True, exist_ok=True)
    rows = list(db.execute("SELECT name,entity_type,aliases,confidence FROM entities ORDER BY entity_type,name"))
    for name, entity_type, aliases, confidence in rows:
        p = root / safe(entity_type)
        p.mkdir(parents=True, exist_ok=True)
        out = p / (safe(name) + ".md")
        values = [x.strip() for x in (aliases or "").split(",") if x.strip()]
        alias_lines = "\n".join("- " + x for x in values) or "- None"
        provenance = list(db.execute("SELECT source,document_id FROM entity_sources WHERE entity_name=? AND entity_type=? ORDER BY source,document_id", (name, entity_type)))
        provenance_lines = "\n".join(f"- {source}: [[{doc_id}]]" for source, doc_id in provenance) or "- None"
        derived_rows = list(db.execute(
            "SELECT source_name,relation,target_name,confidence,rule FROM derived_relations WHERE source_name=? OR target_name=? ORDER BY relation,target_name",
            (name, name),
        )) if _table_exists(db, "derived_relations") else []
        derived_lines = "\n".join(
            f"- [[{s}]] — {rel} → [[{t}]] (confidence: {conf:.3f}; rule: {rule})"
            for s, rel, t, conf, rule in derived_rows
        ) or "- None"
        music_hint = ""
        if entity_type == "MusicTracks":
            music_hint = "\n## Music\n- Track entity from Jacques.\n"
        elif entity_type == "MusicAlbums":
            music_hint = "\n## Music\n- Album entity from Jacques.\n"
        text = (
            "---\n"
            "name: " + yaml_scalar(name) + "\n"
            "type: " + yaml_scalar(entity_type) + "\n"
            "aliases: [" + ", ".join(yaml_scalar(x) for x in values) + "]\n"
            "confidence: " + str(confidence) + "\n"
            "---\n\n"
            "# " + name + "\n\n"
            "## Aliases\n" + alias_lines + "\n\n"
            "## Sources\n" + provenance_lines + "\n\n"
            "## Documents\n"
            + (("\n".join("- [[" + title + "]] — " + source for title, source in db.execute("SELECT d.title,d.source FROM document_entities de JOIN documents d ON d.id=de.document_id WHERE de.entity_name=? AND de.entity_type=? ORDER BY d.title", (name, entity_type)).fetchall())) or "- None")
            + "\n\n"
            "## Relations\n"
            + (("\n".join("- [[" + s + "]] — " + rel + " → [[" + t + "]]" for s, rel, t in db.execute("SELECT source_name,relation,target_name FROM relations WHERE source_name=? OR target_name=? ORDER BY relation,target_name", (name, name)).fetchall())) or "- None")
            + "\n\n"
            "## Mentioned in\n"
            "- Entity backlinks are generated from the canonical database.\n\n"
            "## Derived Relations\n" + derived_lines + "\n"
            + music_hint
        )
        write_atomic(out, text)

def write_entity_moc(db, root):
    root = Path(root) / "entities"
    root.mkdir(parents=True, exist_ok=True)
    rows = list(db.execute("SELECT name,entity_type,aliases,confidence FROM entities ORDER BY entity_type,name"))
    lines = ["---", "title: \"Entity Index\"", "type: \"MOC\"", "---", "", "# Entity Index", "", "> Canonical entities across all connected apps. Each note retains source provenance and relation/document backlinks.", ""]
    current = None
    for name, entity_type, aliases, confidence in rows:
        if entity_type != current:
            if current is not None:
                lines.append("")
            lines.extend([f"## {entity_type}", ""])
            current = entity_type
        lines.append(f"- [[{name}]] — confidence: {confidence:.3f}")
    write_atomic(root / "_Entity Index.md", "\n".join(lines) + "\n")


def write_knowledge_index(db, root):
    root = Path(root)
    root.mkdir(parents=True, exist_ok=True)
    entity_counts = db.execute("SELECT entity_type,COUNT(*) FROM entities GROUP BY entity_type ORDER BY entity_type").fetchall()
    doc_counts = db.execute("SELECT source,COUNT(*) FROM documents GROUP BY source ORDER BY source").fetchall()
    vocab_count = db.execute("SELECT COUNT(*) FROM vocabularies").fetchone()[0]
    relation_count = db.execute("SELECT COUNT(*) FROM relations").fetchone()[0]
    source_entity_count = db.execute("SELECT COUNT(DISTINCT source) FROM entity_sources").fetchone()[0]
    lines = [
        "---", "title: \"Knowledge Index\"", "type: \"MOC\"", "---", "",
        "# Knowledge Index", "",
        "> Nayvadius canonical knowledge layer: Abraham + Abel + Jacques → normalized graph → Obsidian.", "",
        "## System", "",
        f"- [[entities/_Entity Index]] — canonical entities",
        f"- [[vocabulary/_Vocabulary Index]] — vocabulary",
        f"- [[graph.json]] — machine-readable knowledge graph",
        "",
        "## Entity Domains", "",
    ]
    lines.extend(f"- [[entities/{etype}/_Index]] — {count} entities" for etype, count in entity_counts)
    lines += ["", "## Sources", ""]
    lines.extend(f"- **{source}** — {count} documents" for source, count in doc_counts)
    lines += [
        "", "## Cross-Domain Graph", "",
        f"- Entities: **{sum(count for _, count in entity_counts)}**",
        f"- Relations: **{relation_count}**",
        f"- Vocabulary: **{vocab_count}**",
        f"- Source types: **{source_entity_count}**",
        f"- Canonical source bridges: **{db.execute('SELECT COUNT(*) FROM source_bridge_links').fetchone()[0] if _table_exists(db, 'source_bridge_links') else 0}**",
        f"- Entity merge decisions: **{db.execute('SELECT COUNT(*) FROM entity_merge_log').fetchone()[0] if _table_exists(db, 'entity_merge_log') else 0}**",
        "",
        "## Navigation", "",
        "- [[entities/MusicTracks/_Index]] — Jacques tracks",
        "- [[entities/MusicAlbums/_Index]] — Jacques albums",
        "- [[vocabulary/HSK6/_Index]] — HSK 6",
        "- [[vocabulary/HSK7-9/_Index]] — HSK 7–9",
        "",
    ]
    write_atomic(root / "_Knowledge Index.md", "\n".join(lines))

def write_cross_domain_moc(db, root):
    root = Path(root)
    lines = [
        "---", 'title: "Cross-Domain Connections"', 'type: "MOC"', "---", "",
        "# Cross-Domain Connections", "",
        "> Deterministic connections discovered across Abraham, Abel, and Jacques. Derived facts remain explicitly marked.",
        "",
    ]
    try:
        rows = db.execute(
            "SELECT source_name,relation,target_name,confidence,rule FROM derived_relations ORDER BY source_name,target_name,relation"
        ).fetchall()
    except Exception as exc:
        if "no such table" in str(exc):
            rows = []
        else:
            raise
    if rows:
        lines.append("## Entity Graph")
        lines.append("")
        for source, relation, target, confidence, rule in rows:
            lines.append(f"- [[{source}]] — **{relation}** → [[{target}]] — {confidence:.3f} — `{rule}`")
    else:
        lines.append("## Entity Graph")
        lines.append("")
        lines.append("- No derived entity connections yet.")

    lines += ["", "## Abraham ↔ Abel", ""]
    try:
        cross_rows = db.execute(
            """SELECT c.left_name,c.left_type,c.right_id,c.right_kind,c.confidence,c.rule,
                      v.word,v.pinyin
                 FROM cross_domain_links c
                 JOIN vocabularies v ON v.id=c.right_id
                WHERE c.right_kind='vocabulary'
                ORDER BY c.left_name,v.word"""
        ).fetchall()
    except Exception as exc:
        if "no such table" in str(exc):
            cross_rows = []
        else:
            raise
    base_rows = [
        row for row in cross_rows
        if row[1] != "Vocabulary"
    ]
    if base_rows:
        for name, etype, vid, _, confidence, rule, word, pinyin in base_rows:
            lines.append(f"- [[{name}]] ({etype}) ↔ [[{word}]] — {confidence:.3f} — `{rule}`")
    else:
        lines.append("- No deterministic entity↔vocabulary connections yet.")

    lines += ["", "## Abraham ↔ Abel ↔ Jacques", ""]
    try:
        music_rows = db.execute(
            """SELECT left_name,left_type,right_id,right_kind,confidence,rule,provenance
                 FROM cross_domain_links
                WHERE left_type='Vocabulary'
                  AND right_kind IN ('music_track','music_album')
                ORDER BY right_kind,right_id,left_name"""
        ).fetchall()
    except Exception as exc:
        if "no such table" in str(exc):
            music_rows = []
        else:
            raise
    if music_rows:
        for vocab_id, _, music_name, kind, confidence, rule, provenance in music_rows:
            label = "Track" if kind == "music_track" else "Album"
            try:
                word_row = db.execute("SELECT word FROM vocabularies WHERE id=?", (vocab_id,)).fetchone()
                word = word_row[0] if word_row else vocab_id
            except Exception:
                word = vocab_id
            lines.append(
                f"- [[{word}]] ↔ [[{music_name}]] ({label}) — "
                f"{confidence:.3f} — `{rule}`"
            )
    else:
        lines.append("- No deterministic three-way connections yet.")

    lines += ["", "## Source Bridges", ""]
    try:
        bridge_rows = db.execute("SELECT entity_name,entity_type,source_a,source_b,confidence,rule,provenance FROM source_bridge_links ORDER BY source_a,source_b,entity_type,entity_name").fetchall()
    except Exception as exc:
        if "no such table" in str(exc):
            bridge_rows = []
        else:
            raise
    if bridge_rows:
        pair_counts = {}
        for name, etype, source_a, source_b, confidence, rule, provenance in bridge_rows:
            pair_counts[(source_a, source_b)] = pair_counts.get((source_a, source_b), 0) + 1
        lines += ["### By Source Pair", ""]
        for pair, count in sorted(pair_counts.items()):
            lines.append(f"- **{pair[0]} ↔ {pair[1]}** — {count} canonical entities")
        lines += ["", "### Canonical Entity Bridges", ""]
        for name, etype, source_a, source_b, confidence, rule, provenance in bridge_rows:
            payload = json.loads(provenance)
            docs_a = ", ".join(payload.get("sources", {}).get(source_a, {}).get("document_ids", [])) or "—"
            docs_b = ", ".join(payload.get("sources", {}).get(source_b, {}).get("document_ids", [])) or "—"
            lines.append(f"- [[{name}]] ({etype}) — **{source_a} ↔ {source_b}** — {confidence:.3f} — `{rule}` — docs: {docs_a}; {docs_b}")
    else:
        lines.append("- No canonical multi-source bridges yet.")

    write_atomic(root / "_Cross-Domain Connections.md", "\n".join(lines) + "\n")


def write_domain_mocs(db, root):
    root = Path(root) / "entities"
    for entity_type, title in [("MusicTracks", "Music Tracks"), ("MusicAlbums", "Music Albums")]:
        folder = root / entity_type
        folder.mkdir(parents=True, exist_ok=True)
        rows = db.execute("SELECT name,confidence FROM entities WHERE entity_type=? ORDER BY name", (entity_type,)).fetchall()
        lines = ["---", f"title: \"{title}\"", 'type: "MOC"', "---", "", f"# {title}", ""]
        lines.extend(f"- [[{name}]] — confidence: {confidence:.3f}" for name, confidence in rows)
        write_atomic(folder / "_Index.md", "\n".join(lines) + "\n")

def write_vocabulary_from_db(db, root):
    root = Path(root) / "vocabulary"
    root.mkdir(parents=True, exist_ok=True)
    rows = list(db.execute(
        "SELECT id,word,traditional,pinyin,pos,meaning_ko,hsk_levels,wordbooks,source FROM vocabularies ORDER BY word"
    ))
    for vid, word, traditional, pinyin, pos, meaning_ko, hsk_levels, wordbooks, source in rows:
        out = root / (safe(vid) + ".md")
        levels = [x for x in (hsk_levels or "").split("|") if x]
        books = [x for x in (wordbooks or "").split("|") if x]
        links = list(db.execute(
            "SELECT entity_name,entity_type FROM entity_vocabulary_links WHERE vocabulary_id=? ORDER BY entity_name",
            (vid,)
        ))
        entity_lines = "\n".join(f"- [[{name}]] ({etype})" for name, etype in links) or "- None"
        text = (
            "---\n"
            "id: " + yaml_scalar(vid) + "\n"
            "word: " + yaml_scalar(word) + "\n"
            "traditional: " + yaml_scalar(traditional) + "\n"
            "pinyin: " + yaml_scalar(pinyin) + "\n"
            "pos: " + yaml_scalar(pos) + "\n"
            "source: " + yaml_scalar(source) + "\n"
            "hsk_levels: [" + ", ".join(yaml_scalar(x) for x in levels) + "]\n"
            "wordbooks: [" + ", ".join(yaml_scalar(x) for x in books) + "]\n"
            "---\n\n"
            "# " + word + "\n\n"
            "## Meaning\n" + (meaning_ko or "- None") + "\n\n"
            "## Linked entities\n" + entity_lines + "\n\n"
            "## Mentioned in\n"
            + (("\n".join("- [[" + title + "]]" for title, in db.execute("SELECT d.title FROM document_vocabulary_links l JOIN documents d ON d.id=l.document_id WHERE l.vocabulary_id=? ORDER BY d.title", (vid,)).fetchall())) or "- None")
            + "\n"
        )
        write_atomic(out, text)


def write_vocabulary_moc(db, root):
    root = Path(root) / "vocabulary"
    root.mkdir(parents=True, exist_ok=True)
    rows = list(db.execute(
        "SELECT id,word,pinyin,hsk_levels,wordbooks FROM vocabularies ORDER BY word"
    ))
    lines = ["---", "title: \"Vocabulary Index\"", "type: \"MOC\"", "---", "", "# Vocabulary Index", ""]
    for vid, word, pinyin, hsk_levels, wordbooks in rows:
        levels = ", ".join(x for x in (hsk_levels or "").split("|") if x) or "unclassified"
        lines.append(f"- [[{word}]] — {pinyin or '-'} — {levels}")
    write_atomic(root / "_Vocabulary Index.md", "\n".join(lines) + "\n")


def write_hsk_mocs(db, root):
    root = Path(root) / "vocabulary"
    groups = [("HSK6", {"6"}), ("HSK7-9", {"7", "8", "9", "7-9"})]
    for label, wanted in groups:
        rows = []
        for row in db.execute("SELECT word,pinyin,hsk_levels FROM vocabularies ORDER BY word"):
            levels = set(x for x in (row[2] or "").split("|") if x)
            if levels & wanted:
                rows.append(row)
        folder = root / label
        folder.mkdir(parents=True, exist_ok=True)
        lines = ["---", f'title: "{label} Vocabulary"', 'type: "MOC"', "---", "", f"# {label} Vocabulary", ""]
        lines.extend(f"- [[{word}]] — {pinyin or '-'}" for word, pinyin, _ in rows)
        write_atomic(folder / "_Index.md", "\n".join(lines) + "\n")
