from pathlib import Path
def safe(s): return ''.join(c if c.isalnum() or c in ' -_' else '_' for c in s).strip()[:120] or 'untitled'
def yaml_scalar(value):
 value=str(value).replace('\\','\\\\').replace('"','\\\"').replace('\n',' ')
 return '"'+value+'"'
def write_atomic(path,text):
 path=Path(path); tmp=path.with_suffix(path.suffix+'.tmp'); tmp.write_text(text,encoding='utf-8'); tmp.replace(path)
def write_markdown(result,root):
 p=Path(root)/'documents'; p.mkdir(parents=True,exist_ok=True); out=p/(safe(result.document.id)+'.md')
 tags=', '.join(yaml_scalar(x) for x in result.tags)
 ents='\n'.join('- [['+e.name+']] ('+e.entity_type+')' for e in result.entities) or '- None'
 rels='\n'.join('- [['+x.source+']] - '+x.relation+' -> [['+x.target+']]' for x in result.relations) or '- None'
 text=('---\n'+'id: '+yaml_scalar(result.document.id)+'\n'+'title: '+yaml_scalar(result.document.title)+'\n'+'source: '+yaml_scalar(result.document.source)+'\n'+'importance: '+str(result.importance)+'\n'+'document_type: '+yaml_scalar(result.document_type)+'\n'+'tags: ['+tags+']\n---\n\n# '+result.document.title+'\n\n## Summary\n'+result.summary+'\n\n## Korean\n'+result.translation_ko+'\n\n## Entities\n'+ents+'\n\n## Relations\n'+rels+'\n')
 write_atomic(out,text)
def write_entities(entities,root):
 root=Path(root)/'entities'
 for e in entities:
  p=root/safe(e.entity_type); p.mkdir(parents=True,exist_ok=True); out=p/(safe(e.name)+'.md')
  aliases=', '.join(yaml_scalar(x) for x in e.aliases)
  write_atomic(out,
   '---\nname: '+yaml_scalar(e.name)+'\ntype: '+yaml_scalar(e.entity_type)+'\naliases: ['+aliases+']\nconfidence: '+str(e.confidence)+'\n---\n\n# '+e.name+'\n\n## Aliases\n'+('\n'.join('- '+x for x in e.aliases) or '- None')+'\n\n## Mentioned in\n- See document backlinks generated by the knowledge pipeline.\n')


def write_entities_from_db(db, root):
    root = Path(root) / "entities"
    root.mkdir(parents=True, exist_ok=True)
    rows = list(db.execute("SELECT name,entity_type,aliases,confidence FROM entities ORDER BY entity_type,name"))
    for name, entity_type, aliases, confidence in rows:
        p = root / safe(entity_type)
        p.mkdir(parents=True, exist_ok=True)
        out = p / (safe(name) + ".md")
        values = [x.strip() for x in (aliases or "").split(",") if x.strip()]
        alias_lines = "\n".join("- " + x for x in values) or "- None"
        text = (
            "---\n"
            "name: " + yaml_scalar(name) + "\n"
            "type: " + yaml_scalar(entity_type) + "\n"
            "aliases: [" + ", ".join(yaml_scalar(x) for x in values) + "]\n"
            "confidence: " + str(confidence) + "\n"
            "---\n\n"
            "# " + name + "\n\n"
            "## Aliases\n" + alias_lines + "\n\n"
            "## Mentioned in\n"
            "- See document backlinks generated by the knowledge pipeline.\n"
        )
        write_atomic(out, text)

def write_entity_moc(db, root):
    root = Path(root) / "entities"
    root.mkdir(parents=True, exist_ok=True)
    rows = list(db.execute("SELECT name,entity_type,aliases,confidence FROM entities ORDER BY entity_type,name"))
    lines = ["---", "title: \"Entity Index\"", "type: \"MOC\"", "---", "", "# Entity Index", ""]
    current = None
    for name, entity_type, aliases, confidence in rows:
        if entity_type != current:
            if current is not None:
                lines.append("")
            lines.extend([f"## {entity_type}", ""])
            current = entity_type
        lines.append(f"- [[{name}]] — confidence: {confidence:.3f}")
    write_atomic(root / "_Entity Index.md", "\n".join(lines) + "\n")


def write_vocabulary_from_db(db, root):
    root = Path(root) / "vocabulary"
    root.mkdir(parents=True, exist_ok=True)
    rows = list(db.execute(
        "SELECT id,word,traditional,pinyin,pos,meaning_ko,hsk_levels,wordbooks,source FROM vocabularies ORDER BY word"
    ))
    for vid, word, traditional, pinyin, pos, meaning_ko, hsk_levels, wordbooks, source in rows:
        out = root / (safe(vid) + ".md")
        levels = [x for x in (hsk_levels or "").split("|") if x]
        books = [x for x in (wordbooks or "").split("|") if x]
        links = list(db.execute(
            "SELECT entity_name,entity_type FROM entity_vocabulary_links WHERE vocabulary_id=? ORDER BY entity_name",
            (vid,)
        ))
        entity_lines = "\n".join(f"- [[{name}]] ({etype})" for name, etype in links) or "- None"
        text = (
            "---\n"
            "id: " + yaml_scalar(vid) + "\n"
            "word: " + yaml_scalar(word) + "\n"
            "traditional: " + yaml_scalar(traditional) + "\n"
            "pinyin: " + yaml_scalar(pinyin) + "\n"
            "pos: " + yaml_scalar(pos) + "\n"
            "source: " + yaml_scalar(source) + "\n"
            "hsk_levels: [" + ", ".join(yaml_scalar(x) for x in levels) + "]\n"
            "wordbooks: [" + ", ".join(yaml_scalar(x) for x in books) + "]\n"
            "---\n\n"
            "# " + word + "\n\n"
            "## Meaning\n" + (meaning_ko or "- None") + "\n\n"
            "## Linked entities\n" + entity_lines + "\n"
        )
        write_atomic(out, text)
